dependencies:
  post:
    - bundle exec appraisal install
  test:
    pre:
      - bundle exec appraisal rake db:create
      - bundle exec appraisal rake db:migrate
    override:
      - bundle exec appraisal rspec
