build_job: &build_job
  working_directory: ~/wice_grid
  steps:
    - checkout

    # Install PhantomJS (if not found in cache)
    - run:
        name: Install phantomjs
        command: |
          if ! [ $(which phantomjs) ]; then
          sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
          fi

          sudo chmod ugo+x /usr/local/bin/phantomjs

    # Restore Cached Dependencies
    - type: cache-restore
      name: Restore bundle cache
      key: wice_grid-{{ checksum "Gemfile.lock" }}

    # Bundle install dependencies
    - run: bundle install --path vendor/bundle

    # Install Appraisal gemfiles
    - run: bundle exec appraisal install

    # Cache Dependencies
    - type: cache-save
      name: Store bundle cache
      key: wice_grid-{{ checksum "Gemfile.lock" }}
      paths:
      - vendor/bundle

    # Run the tests
    - run: bundle exec appraisal rspec

version: 2
jobs:
  build-ruby24:
    <<: *build_job
    docker:
      - image: circleci/ruby:2.4
        environment:
          RAILS_ENV: test
  build-ruby25:
    <<: *build_job
    docker:
      - image: circleci/ruby:2.5
        environment:
          RAILS_ENV: test
  build-ruby26:
    <<: *build_job
    docker:
      - image: circleci/ruby:2.6
        environment:
          RAILS_ENV: test

workflows:
  version: 2
  build:
    jobs:
    - build-ruby24
    - build-ruby25
